=== AbrahamQM/CFGS-DAW/Lenguaje de marcas/Ut 4 Definición de esquemas y vocabularios en xml/tarea/quintana_mico_abraham_torneo.dtd
<!-- Elemento principal torneo -->
<!ELEMENT torneo (participantes)>
<!-- Atributos de cada torneo -->
<!ATTLIST torneo
    anio CDATA #REQUIRED
    anteriorGanador IDREF #REQUIRED>

<!-- Elemento participantes del torneo-->
<!ELEMENT participantes (participante+)>
<!-- Elemento participante -->
<!ELEMENT participante (nombre, edad, pais, cabezaDeSerie?)>
<!-- Atributos de cada participante -->
<!ATTLIST participante
    idP ID #REQUIRED
    pareja IDREF #REQUIRED>

<!-- nombre -->
<!ELEMENT nombre (#PCDATA)>
<!-- edad -->
<!ELEMENT edad (#PCDATA)>
<!-- pais -->
<!ELEMENT pais (#PCDATA)>
<!-- cabezaDeSerie -->
<!ELEMENT cabezaDeSerie (#PCDATA)>

=== AbrahamQM/CFGS-DAW/Lenguaje de marcas/Ut 4 Definición de esquemas y vocabularios en xml/tarea/quintana_mico_abraham_torneo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE torneo SYSTEM "quintana_mico_abraham_torneo.dtd">
<torneo anio="2022" anteriorGanador="P1">
    <participantes>
        <participante idP="P1" pareja="P2">
            <nombre>Manuel Perez</nombre>
            <edad>23</edad>
            <pais>España</pais>
            <cabezaDeSerie>SI</cabezaDeSerie>
        </participante>
        <participante idP="P2" pareja="P1">
            <nombre>Manuel Gómez</nombre>
            <edad>25</edad>
            <pais>España</pais>
            <cabezaDeSerie>NO</cabezaDeSerie>
        </participante>
        <participante idP="P3" pareja="P4">
            <nombre>Ana Puertas</nombre>
            <edad>23</edad>
            <pais>España</pais>
            <cabezaDeSerie>SI</cabezaDeSerie>
        </participante>
        <participante idP="P4" pareja="P3">
            <nombre>Paco Fraile</nombre>
            <edad>45</edad>
            <pais>España</pais>
            <cabezaDeSerie>NO</cabezaDeSerie>
        </participante>
    </participantes>
</torneo>
